image:
  repository: ghcr.io/axoflow/syslog-ng
  pullPolicy: IfNotPresent
  tag: "4.1.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

daemonset:
  enabled: true
  labels: {}
  annotations: {}
  affinity: {}
  nodeSelector: {}
  resources: {}
  tolerations: []
  hostAliases: []
  secretMounts: []
  extraVolumes: []
  securityContext: {}
  maxUnavailable: 1
  hostNetworking: false

config: |
  @version: 4.1
  @include "scl.conf"

  options {
    stats(
      level(1)
    );
  };

  source s_kubernetes {
    kubernetes();
  };

  destination d_local { # TODO: where should we send our logs?
    file("/tmp/out.log");
  };

  log {
    source(s_kubernetes);
    destination(d_local);
  };

# TODO: kubernetes src should have a toggle
# TODO: syslog-ng-ctl healthcheck should be called somewhere

rbac:
  create: true
  extraRules: []

openShift:
  enabled: false
  securityContextConstraints:
    create: true
    annotations: {}

serviceAccount:
  create: true
  annotations: {}

namespace: ""
podAnnotations: {}
podSecurityContext: {}
#   fsGroup: 2000
securityContext: {}
resources: {}
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
updateStrategy: RollingUpdate
priorityClassName: ""
dnsConfig: {}
hostAliases: []
secretMounts: []
extraVolumes: []
## How long (in seconds) a pod may take to exit (useful with lifecycle hooks to ensure lb deregistration is done)
##
terminationGracePeriodSeconds: 30
