replicaCount: 1

image:
  repository: ghcr.io/axoflow/syslog-ng
  pullPolicy: IfNotPresent
  tag: "4.1.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

daemonset:
  enabled: true
  labels: {}
  annotations: {}
  affinity: {}
  nodeSelector: {}
  resources: {}
  tolerations: []
  hostAliases: []
  secretMounts: []
  extraVolumes: []
  securityContext: {}
  maxUnavailable: 1
  hostNetworking: false

config: |
  @version: 4.1
  @include "scl.conf"

  options {
    stats(
      level(1)
    );
  };

  source s_kubernetes {
    kubernetes();
  };

  destination d_local { # TODO: where should we send our logs?
    file("/tmp/out.log");
  };

  log {
    source(s_kubernetes);
    destination(d_local);
  };

# TODO: kubernetes src should have a toggle
# TODO: syslog-ng-ctl healthcheck should be called somewhere

serviceAccount:
  create: true
  annotations: {}
  extraRules: []

namespace: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
updateStrategy: RollingUpdate
priorityClassName: ""
dnsConfig: {}
hostAliases: []
secretMounts: []
extraVolumes: []
terminationGracePeriodSeconds: 30
