replicaCount: 1

image:
  repository: ghcr.io/axoflow/syslog-ng
  pullPolicy: IfNotPresent
  tag: "4.1.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

daemonset:
  enabled: true
  labels: {}
  annotations: {}
  affinity: {}
  nodeSelector: {}
  resources: {}
  tolerations: []
  hostAliases: []
  secretMounts: []
  extraVolumes: []
  securityContext: {}
  maxUnavailable: 1
  hostNetworking: false

config:
  raw: ""  # Use this to manually set the contents of the syslog-ng.conf file.
  sources:
    kubernetes:
      enabled: true
  destinations:
    network: []
#   E.g.:
#     - transport: tcp
#       address: localhost
#       port: 12345
#       template: "$(format-json .*)"
    opensearch: []
#   E.g.:
#     - address: 10.104.232.94
#       index: "test-axoflow-index"
#       user: "admin"
#       password: "admin"
#       tls:
#         CAFile: "/path/to/CAFile.pem"
#         CADir: "/path/to/CADir/"
#         Cert: "/path/to/Cert.pem"
#         Key: "/path/to/Key.pem"
#         peerVerify: false
#         template: "$(format-json .*)"

serviceAccount:
  create: true
  annotations: {}
  extraRules: []

namespace: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
updateStrategy: RollingUpdate
priorityClassName: ""
dnsConfig: {}
hostAliases: []
secretMounts: []
extraVolumes: []
terminationGracePeriodSeconds: 30
