replicaCount: 1

image:
  repository: ghcr.io/axoflow/syslog-ng
  pullPolicy: IfNotPresent
  tag: "4.1.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

daemonset:
  enabled: true
  labels: {}
  annotations: {}
  affinity: {}
  nodeSelector: {}
  resources: {}
  tolerations: []
  hostAliases: []
  secretMounts: []
  extraVolumes: []
  securityContext: {}
  maxUnavailable: 1
  hostNetworking: false

config:
  raw: ""  # Use this to manually set the contents of the syslog-ng.conf file.
  sources:
    kubernetes:
      enabled: true
  destinations:
    network: []
#   E.g.:
#     - transport: tcp
#       address: localhost
#       port: 12345

serviceAccount:
  create: true
  annotations: {}
  extraRules: []

namespace: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
updateStrategy: RollingUpdate
priorityClassName: ""
dnsConfig: {}
hostAliases: []
secretMounts: []
extraVolumes: []
terminationGracePeriodSeconds: 30
