apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "axosyslog-collector.labels" . | nindent 4 }}
  name: {{ include "axosyslog-collector.fullname" . }}
data:
{{- if .Values.config.raw }}
  syslog-ng.conf: {{ tpl (toYaml .Values.config.raw) . | indent 4 }}
{{- else }}
  syslog-ng.conf: |
    @version: {{ regexFind "^[0-9]+\\.[0-9]+" .Values.config.version | default "current" }}
    @include "scl.conf"

    options {
      stats(
        level({{ .Values.config.stats.level }})
      );
    };

    log {
{{- if .Values.config.sources.kubernetes.enabled }}
      source { kubernetes(); };
{{- end }}
{{- range .Values.config.sources.opentelemetry }}
      source {
        opentelemetry(
  {{- if .port }}
            port({{ .port }})
  {{- end }}
        );
      };
{{- end }}
{{- if .Values.config.parsers.opentelemetry.enabled }}
      parser {
        opentelemetry();
      };
{{- end }}
{{- range .Values.config.destinations.file }}
      destination {
        file(
          {{ .path | quote }}
  {{- if .template }}
          template({{ .template | quote }})
  {{- end }}
  {{- if .extraOptionsRaw }}
          {{ .extraOptionsRaw }}
  {{- end }}
        );
      };
{{- end }}
{{- range .Values.config.destinations.network }}
      destination {
        network(
          {{ .address | quote }}
          port({{ .port }})
          transport({{ .transport }})
  {{- if .template }}
          template({{ .template | quote }})
  {{- end }}
  {{- if .extraOptionsRaw }}
          {{ .extraOptionsRaw }}
  {{- end }}
        );
      };
{{- end }}
{{- range .Values.config.destinations.opensearch }}
      destination {
        elasticsearch-http(
          url("https://{{ .address }}:9200/_bulk")
          index({{ .index | quote }})
          type("")
  {{- if .template }}
          template({{ .template | quote }})
  {{- end }}
  {{- if .user }}
          user({{ .user | quote }})
  {{- end }}
  {{- if .password }}
          password({{ .password | quote }})
  {{- end }}
  {{- if .tls }}
          tls(
    {{- if .tls.CAFile }}
            ca-file({{ .tls.CAFile }})
    {{- end }}
    {{- if .tls.CADir }}
            ca-dir({{ .tls.CADir }})
    {{- end }}
    {{- if .tls.Cert }}
            cert-file({{ .tls.Cert }})
    {{- end }}
    {{- if .tls.Key }}
            key-file({{ .tls.Key }})
    {{- end }}
    {{- if .tls.peerVerify }}
            peer-verify(yes)
    {{- else }}
            peer-verify(no)
    {{- end }}
          )
  {{- end }}
  {{- if .extraOptionsRaw }}
          {{ .extraOptionsRaw }}
  {{- end }}
        );
      };
{{- end }}
{{- range .Values.config.destinations.opentelemetry }}
      destination {
        opentelemetry(
          url({{ tpl .url $ | quote }})
  {{- if .extraOptionsRaw }}
          {{ .extraOptionsRaw }}
  {{- end }}
        );
      };
{{- end }}
    };
{{- end }}
