{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "syslog-ng-collector.serviceAccountName" . }}
  namespace: {{ include "syslog-ng-collector.namespace" . }}
  labels:
    {{- include "syslog-ng-collector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
