[tool.black]
line-length = 120

[tool.mypy]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "azure.*"
follow_imports = "skip"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "boto3.*"
follow_imports = "skip"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "botocore.*"
follow_imports = "skip"
ignore_missing_imports = true
