image:
  repository: ghcr.io/axoflow/axosyslog
  pullPolicy: IfNotPresent
  tag: ""
  extraArgs: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

daemonset:
  enabled: true
  labels: {}
  annotations: {}
  affinity: {}
  nodeSelector: {}
  resources: {}
  tolerations: []
  hostAliases: []
  secretMounts: []
  extraVolumes: []
  securityContext: {}
  maxUnavailable: 1
  hostNetworking: false

metricsExporter:
  enabled: false  # deploy the axosyslog Deamonset with the axosyslog-metrics-exporter sidecar
  image:
    repository: ghcr.io/axoflow/axosyslog-metrics-exporter
    tag: latest
    pullPolicy: ~ # use k8s default behavior (Always for :latest, IfNotPresent otherwise)
  resources: {}
  securityContext: {}

podMonitor:
  enabled: false  # deploy the PodMonitor CR for Prometheus Operator (requires metricsExporter.enabled)
  labels: {}
  annotations: {}

config:
  raw: ""  # Use this to manually set the contents of the syslog-ng.conf file.
  version: ""
  stats:
    level: 2
  sources:
    kubernetes:
      enabled: true
#     E.g.:
#     prefix: "k8s~"
#     keyDelimiter: "~"
    opentelemetry: []
#   E.g.:
#     - port: 4317
  parsers:
    opentelemetry:
      enabled: false
  destinations:
    file: []
#   E.g.:
#     - path: "/dev/stdout"
#       template: "$(format-json .*)"
#       extraOptionsRaw: "create-dirs(yes)"
    network: []
#   E.g.:
#     - transport: tcp
#       address: localhost
#       port: 12345
#       template: "$(format-json .*)"
#       extraOptionsRaw: "time-reopen(10)"
    opensearch: []
#   E.g.:
#     - address: 10.104.232.94
#       index: "test-axoflow-index"
#       user: "admin"
#       password: "admin"
#       tls:
#         CAFile: "/path/to/CAFile.pem"
#         CADir: "/path/to/CADir/"
#         Cert: "/path/to/Cert.pem"
#         Key: "/path/to/Key.pem"
#         peerVerify: false
#         template: "$(format-json .*)"
#       extraOptionsRaw: "time-reopen(10)"
    opentelemetry: []
#   E.g.:
#     - url: "10.104.232.95:4317"
#       extraOptionsRaw: "time-reopen(10)"

rbac:
  create: true
  extraRules: []

openShift:
  enabled: false
  securityContextConstraints:
    create: true
    annotations: {}

service:
  create: false
  extraPorts: []

serviceAccount:
  create: true
  annotations: {}

namespace: ""
podAnnotations: {}
podSecurityContext: {}
#   fsGroup: 2000
securityContext: {}
resources: {}
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
updateStrategy: RollingUpdate
priorityClassName: ""
dnsConfig: {}
hostAliases: []
secretMounts: []
extraVolumes: []
## How long (in seconds) a pod may take to exit (useful with lifecycle hooks to ensure lb deregistration is done)
##
terminationGracePeriodSeconds: 30
