{{- if .Values.collector.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "axosyslog.fullname" . }}
  namespace: {{ include "axosyslog.namespace" . }}
  labels:
    app: "{{ template "axosyslog.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    {{- if .Values.collector.labels }}
    {{- range $key, $value := .Values.collector.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- if .Values.collector.annotations }}
  annotations:
    {{- range $key, $value := .Values.collector.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: "{{ template "axosyslog.fullname" . }}"
      release: {{ .Release.Name | quote }}
  updateStrategy:
    {{- if eq .Values.updateStrategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.collector.maxUnavailable }}
    {{- end }}
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      {{- if .Values.podAnnotation }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      name: "{{ template "axosyslog.fullname" . }}"
      labels:
        app: "{{ template "axosyslog.fullname" . }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        {{- if .Values.collector.labels }}
        {{- range $key, $value := .Values.collector.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "axosyslog.serviceAccountName" . }}
      {{- end}}
      tolerations: {{ toYaml ( .Values.tolerations | default .Values.collector.tolerations ) | nindent 8 }}
      nodeSelector: {{ toYaml ( .Values.nodeSelector | default .Values.collector.nodeSelector ) | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      affinity: {{ toYaml ( .Values.affinity | default .Values.collector.affinity ) | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.collector.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig: {{ toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases | default .Values.collector.hostAliases }}
      hostAliases: {{ toYaml ( .Values.hostAliases | default .Values.collector.hostAliases ) | nindent 8 }}
      {{- end }}
      volumes:
      {{- range .Values.secretMounts | default .Values.collector.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
        - name: config
          configMap:
            name: {{ include "axosyslog.fullname" . }}
        - name: var-log
          hostPath:
            path: /var/log
        - name: var-lib-docker-containers
          hostPath:
            path: /var/lib/docker/containers
        - name: var-run-docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: var-lib-syslog-ng
          emptyDir: {}
      {{- if .Values.extraVolumes | default .Values.collector.extraVolumes }}
{{ toYaml ( .Values.extraVolumes | default .Values.collector.extraVolumes ) | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: "axosyslog"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          {{- if .Values.image.extraArgs }}
          args:
{{ toYaml .Values.image.extraArgs | indent 12 }}
          {{- end }}
          resources:
{{ toYaml ( .Values.resources | default .Values.collector.resources ) | indent 12 }}
          securityContext: {{ toYaml ( .Values.podSecurityContext | default .Values.collector.securityContext ) | nindent 12 }}
          volumeMounts:
            {{- range .Values.secretMounts | default .Values.collector.secretMounts }}
            - name: {{ .name }}
              mountPath: {{ .path }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            - name: config
              mountPath: /etc/syslog-ng/syslog-ng.conf
              subPath: syslog-ng.conf
            - name: var-log
              mountPath: /var/log
            - name: var-lib-docker-containers
              mountPath: /var/lib/docker/containers
            - name: var-run-docker-sock
              mountPath: /var/run/docker.sock
            - name: var-lib-syslog-ng
              mountPath: /var/lib/syslog-ng
          {{- if .Values.extraVolumeMounts | default .Values.collector.extraVolumeMounts }}
{{ toYaml (.Values.extraVolumeMounts | default .Values.collector.extraVolumeMounts ) | indent 12 }}
          {{- end }}
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            exec:
              command: ["syslog-ng-ctl", "healthcheck", "--timeout", "5"]
        {{- if .Values.metricsExporter.enabled }}
        - name: "metrics-exporter"
          image: "{{ .Values.metricsExporter.image.repository }}:{{ .Values.metricsExporter.image.tag }}"
          imagePullPolicy: "{{ .Values.metricsExporter.image.pullPolicy }}"
          args:
            - --socket.path=/var/lib/syslog-ng/syslog-ng.ctl
          volumeMounts:
            - name: var-lib-syslog-ng
              mountPath: /var/lib/syslog-ng
          ports:
            - containerPort: 9577
              name: exporter
              protocol: TCP
          resources: {{ toYaml ( .Values.metricsExporter.resources ) | nindent 12 }}
          securityContext: {{ toYaml ( .Values.metricsExporter.securityContext | default .Values.collector.securityContext ) | nindent 12 }}
        {{- end }}
{{- end }}
