name: AxoSyslog charts linter

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: charts/axosyslog

jobs:
  axosyslog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Linter
        run: |
          docker run -v${PWD}:${PWD} alpine/helm lint ${PWD}
